arcoiris=("Azul","Verde","Rojo", "Amarrilo")
print(arcoiris)
print("--Longitud arcoiris--")
print(len(arcoiris))
animales=("Pantera",20,"Estatura", 1.7)
print(animales)
print("Elementos de la tupla")
print(animales[1])
rateros=("Juan","Ana","Pedro")
y = list(rateros)
y[0]= "polancas"
x = tuple(y)
print(x)
print("Agregando elementos")
Nanimal=("Boby","Chettos")
y = list(Nanimal)
print(y)
y.append("Tontolin")
otratupla = tuple(y)

print(otratupla)
print("Uso de for en tuplas")
for elcolor in arcoiris:
    print(elcolor)